package InicioJava;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Form.java
 *
 * Created on 01-19-2012, 06:54:50 AM
 */
/**
 *
 * @author NIGHTMARE
 */
public class Form extends javax.swing.JFrame {

    /** Creates new form Form */
    public Form() {
        initComponents();
        definircombobox();
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTextoPrincipal = new javax.swing.JLabel();
        txtNum1 = new javax.swing.JTextField();
        txtNum2 = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        getContentPane().setLayout(null);

        lblTextoPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTextoPrincipal.setText("Suma");
        lblTextoPrincipal.setMaximumSize(new java.awt.Dimension(80, 14));
        lblTextoPrincipal.setMinimumSize(new java.awt.Dimension(80, 14));
        lblTextoPrincipal.setPreferredSize(new java.awt.Dimension(80, 14));
        getContentPane().add(lblTextoPrincipal);
        lblTextoPrincipal.setBounds(90, 20, 260, 14);

        txtNum1.setMinimumSize(new java.awt.Dimension(6, 30));
        txtNum1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNum1FocusGained(evt);
            }
        });
        getContentPane().add(txtNum1);
        txtNum1.setBounds(150, 70, 90, 20);
        getContentPane().add(txtNum2);
        txtNum2.setBounds(150, 110, 90, 20);

        btnCalcular.setText("Calcular");
        btnCalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalcularMouseClicked(evt);
            }
        });
        getContentPane().add(btnCalcular);
        btnCalcular.setBounds(140, 200, 100, 23);
        getContentPane().add(txtTotal);
        txtTotal.setBounds(150, 150, 90, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(30, 110, 90, 30);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 240, 210, 14);

        setBounds(0, 0, 416, 338);
    }// </editor-fold>//GEN-END:initComponents

private void txtNum1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNum1FocusGained

}//GEN-LAST:event_txtNum1FocusGained

private void btnCalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularMouseClicked
    int num1,num2,total=0;
    num1=Integer.parseInt(this.txtNum1.getText());
    num2=Integer.parseInt(this.txtNum2.getText());
    if(this.jComboBox1.getSelectedIndex()==0){
        total=num1+num2;
    }else if(this.jComboBox1.getSelectedIndex()==1){
        total=num1-num2;        
    }else if(this.jComboBox1.getSelectedIndex()==2){
        total=num1*num2;        
    }else if(this.jComboBox1.getSelectedIndex()==3){
        total=num1/num2;        
    }
    this.txtTotal.setText(String.valueOf(total));
}//GEN-LAST:event_btnCalcularMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Form().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTextoPrincipal;
    private javax.swing.JTextField txtNum1;
    private javax.swing.JTextField txtNum2;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private void definircombobox() {
        this.lblTextoPrincipal.setText("Hola a todos feos, honestamente simplemente muchas veces no comprendo esto");
        this.jLabel1.setText("Hey que tal como están");
        this.jComboBox1.removeAllItems();
        this.jComboBox1.addItem("Sumar");
        this.jComboBox1.addItem("Restar");
        this.jComboBox1.addItem("Multiplicar");
        this.jComboBox1.addItem("Dividir");        
    }
}
