/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * prueba.java
 *
 * Created on 03-09-2012, 09:05:10 AM
 */
package SimularTablero;

import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.border.Border;

/**
 *
 * @author NIGHTMARE
 */
public class prueba extends javax.swing.JFrame {
    Object objetos[][];
    /** Creates new form prueba */
    public prueba() {
        initComponents();
        this.setSize(600, 600);
        objetos=new Object[5][5];
        iniciarObjetos();
        addListener();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-584)/2, (screenSize.height-562)/2, 584, 562);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new prueba().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private void iniciarObjetos(){
        
        for(int i=0;i<objetos.length;i++){
            for(int e=0;e<objetos[i].length;e++){
                objetos[i][e]=new JLabel();
                ((JLabel)objetos[i][e]).setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));                
                ((JLabel)objetos[i][e]).setBounds(100*e+35,100*i+35,100,100);
            }            
        }
        for(int i=0;i<objetos.length;i++){
            for(int e=0;e<objetos.length;e++){
                this.getContentPane().add(((JLabel)objetos[i][e]));
            }
        }
        
        
    }
    public void validarMovimiento(int fila,int cola){
        //Ejemplo de como validar un movimiento....
        
//        boolean val=verificarMovimiento(fila,cola);
//        if(val==true){
//            String pathNegro=getClass().getResource("421876_386943434666879_280246188669938_1440827_501410493_n.jpg").getPath();
//            String pathBlanco=getClass().getResource("blanca.jpg").getPath();
//            ImageIcon imagen;
//            if(turno==0){
//                
//                imagen=new ImageIcon(pathNegro);
//                
//            }else{
//                imagen=new ImageIcon(pathBlanco);
//            }
//            ImageIcon red=new ImageIcon(imagen.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT));
//            ((JLabel)objetos[fila][cola]).setIcon(red);    
        ImageIcon image=new ImageIcon(getClass().getResource("421876_386943434666879_280246188669938_1440827_501410493_n.jpg").getPath());
        ImageIcon imagen=new ImageIcon(image.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT));
        ((JLabel)this.objetos[fila][cola]).setIcon(imagen);
        
    }

    private void addListener() {
        for(int i=0;i<objetos.length;i++){
            for(int j=0;j<objetos[i].length;j++){
                final int fila=i;
                final int col=j;
                ((JLabel)objetos[i][j]).addMouseListener(new MouseAdapter(){
                    @Override
                    public void mouseClicked(MouseEvent e){
                        validarMovimiento(fila,col);
                    }
                });
            }
        }
    }
}
